### ISSUE TITLE
emerging need: effective computing next steps after cluster 101

### ISSUE THREAD

**Issue by vortexing** [fhdsl/FH_Cluster_102#6]
Hey @avahoffman and @carriewright11  we're needing something after cluster 101 that gets at how to use the Hutch cluster a bit more effectively so we can help folks adjust their usage of the cluster.  I'm realizing I'm struggling to make the documents needed to help people realize that their use of the cluster via whatever mechanism they're using now, could be more effective if they learned a little bit.  

The outline we have of "Ways to do Computing" right now is roughly:

Modes and what they are best for:
Rhino:
- login nodes
- see what software you can use
- do small, interactive jobs
- test small jobs prior to scaling up
- can run cronjobs from here to schedule things to happen regularly

Grabnode is a convenience for:
- runs one big job with limited configuration options
- not sure what this is best for???!?!

SLURM job submission to gizmo:
- making jobs resilient to connectivity issues (grabnode sessions end your job if you lose connectivity)
- no need to babysit the job this way
-  generates job logs for troubleshooting
- uses the SLURM scheduler and better lab job allocation (helps you get resources sooner and in coordination with the rest of your lab and the Hutch users more broadly)
- srun, sbatch, etc. gives you more control and options for configuration that let your jobs run better in many ways

Workflow managers:
- good when you have multi-step processes that need to occur together
- good when you're working on multiple different workflows at the same time
- want to leverage the cluster allocation very efficiently by breaking jobs up
- want to prepare a workflow for better reproducibility, sharing, and expanding to the cloud

Cloud computing: 
- once a workflow has been optimized (likely using a workflow manager above), leveraging the cloud for large, production workflows can help your lab's usage of the cluster while also encouraging reproducibility
- Workflows can ideally be run by others, not just those with access to the Hutch resources

**Comment by vortexing** [comment]
Could cluster 102 be this document?  Then we can keep expanding on the code and other topics in another class?

**Comment by avahoffman** [comment]
Sure, I think cluster 201 could cover some of these topics. Cloud computing should be separate, but could be mentioned.

**Comment by vortexing** [comment]
MAybe just like what you can do on a local cluster in order to THEN move to the cloud. There are certainly some things we can do like shifting to docker containers and really optimizing the compute resources requested for tasks, and dealing with tar'ing reference data so it'll work in an object store that are best to do before even touching the cloud.

**Comment by vortexing** [comment]
OK, closing this here b/c I used this as the outline for Cluster 201.  ;)
